name: test_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  mockito: ^5.0.17
  nasa_apod_core:
    path: ../core
    
dev_dependencies:
  build_runner: ^2.4.8
  faker: 2.0.0 # 2.0.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
  mocktail: 0.1.4 
  network_image_mock: 2.0.1

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
