name: nasa_apod_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # alice: ^0.4.1
  cached_network_image: ^3.3.0
  connectivity_plus: ^3.0.6
  dartz: ^0.10.1
  delayed_display: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  # flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  # google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  localstorage: ^4.0.1+4
  responsive_builder: ^0.7.0
  soundpool: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  faker: 2.0.0 #2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
  mocktail: 0.1.4 #1.0.2
  network_image_mock: 2.0.1

flutter:
  uses-material-design: true

# fonts:
#   - family: Secular_One
#     fonts:
#       - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf

# build_runner:
#   scripts:
#     buildDel: dart run build_runner build --delete-conflicting-outputs
#     watchDel: dart run build_runner watch --delete-conflicting-outputs
#     watch: dart run build_runner watch
