name: nasa_apod_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  nasa_apod_design_system:
    path: ../design_system
  nasa_apod_core:
    path: ../core
  equatable: ^2.0.3
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  go_router: ^13.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_utils:
    path: ../test_utils

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/