name: nasa_apod_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.6.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  # gap: ^2.0.0
  gap: ^3.0.1
  # sliver_tools: ^0.2.5
  sliver_tools: ^0.2.12
  flutter_svg: ^1.0.3
  tap_builder: ^0.3.4

dev_dependencies:
  test_utils:
    path: ../test_utils 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  assets:
    - assets/images/
  fonts:
    - family: apod_icons
      fonts:
        - asset: packages/nasa_apod_design_system/fonts/apod_icons.ttf
    - family: Poppins
      fonts:
        - asset: packages/nasa_apod_design_system/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: packages/nasa_apod_design_system/fonts/Poppins-Bold.ttf
          weight: 700